-- Enable RLS on all critical tables
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DriverComplianceDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Job" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parcel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SettlementBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MediaAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountingEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BusinessAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contract" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RateRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Quote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CarrierProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CarrierRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FleetVehicle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ComplianceDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HRRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimeOffRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payslip" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountingIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VehicleClass" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PricingRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayoutRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuoteRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuoteLineItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ManualReviewCase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PageContent" ENABLE ROW LEVEL SECURITY;

-- Deny all by default for anon/authenticated (Prisma connects as postgres/superuser which bypasses RLS)
-- The only exception is allowing anon to read driver locations via Supabase Realtime
CREATE POLICY "Allow public read for driver location"
  ON "User"
  FOR SELECT
  TO anon
  USING (role = 'driver');
